# port server
server.port=8080

# konfigurasi H2 (database in-memory, data hilang saat app dimatikan)
spring.datasource.url=jdbc:h2:mem:warehousedb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# aktifkan H2 Console untuk cek isi database via browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# konfigurasi JPA dan Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# izinkan data.sql dijalankan setelah schema terbentuk
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.application.name=warehouse-management
